import {
  Organization,
  User,
  AdmissionAgent,
  KnowledgeDocument,
  FAQItem,
  CourseItem,
  CallRecord,
  LeadRecord,
  FollowUpItem,
  PhoneNumberRecord,
  SubscriptionPlan,
  AnalyticsSummary,
} from "@/types";

export const mockUser: User = {
  id: "usr_001",
  name: "Dr. K. S. Rao",
  email: "admissions@abccollege.edu.in",
  role: "admin",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  organizationId: "org_abc_001",
};

export const mockOrganization: Organization = {
  id: "org_abc_001",
  name: "ABC Institute of Technology & Sciences",
  type: "college",
  tagline: "Empowering Next-Gen Engineers & Leaders Since 2004",
  website: "https://www.abccollege.edu.in",
  city: "Hyderabad",
  state: "Telangana",
  phone: "+91 80 4719 8800",
  email: "admissions@abccollege.edu.in",
  onboardingCompleted: true,
};

export const mockAgent: AdmissionAgent = {
  id: "agt_adm_001",
  organizationId: "org_abc_001",
  name: "ABC Admission AI Counsellor",
  status: "active",
  defaultLanguage: "en",
  supportedLanguages: ["en", "hi", "te"],
  voiceId: "voice_priya_indian_multilingual",
  voiceGender: "female",
  voiceSpeed: 1.0,
  greetingMessage:
    "Namaste and welcome to ABC Institute of Technology Admissions! I can assist you with courses, fee structures, eligibility, hostel facilities, and scholarship details. How may I help you today?",
  fallbackMessage:
    "I do not have specific verified details regarding that in my current knowledge base. Would you like me to connect you directly with our senior admission counsellor?",
  confidenceThreshold: 0.85,
  humanHandoffNumber: "+91 98480 22338",
  handoffTriggers: {
    callerRequested: true,
    lowConfidence: true,
    feeNegotiation: true,
    urgentDeadline: true,
  },
  businessHours: {
    enabled: true,
    startTime: "08:30",
    endTime: "19:30",
    timezone: "Asia/Kolkata",
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    afterHoursAction: "ai_only",
  },
  lastUpdated: "2026-08-30T10:30:00Z",
};

export const mockCourses: CourseItem[] = [
  {
    id: "crs_001",
    organizationId: "org_abc_001",
    name: "B.Tech Computer Science & Engineering (CSE)",
    code: "BTECH-CSE",
    degree: "B.Tech",
    durationYears: 4,
    annualFeeINR: 140000,
    eligibility: "10+2 with MPC (Maths, Physics, Chem) minimum 60% or valid TSEAMCET / JEE Main rank.",
    totalSeats: 240,
    availableSeats: 48,
    applicationDeadline: "2026-09-15",
  },
  {
    id: "crs_002",
    organizationId: "org_abc_001",
    name: "B.Tech Artificial Intelligence & Machine Learning (AI&ML)",
    code: "BTECH-AIML",
    degree: "B.Tech",
    durationYears: 4,
    annualFeeINR: 150000,
    eligibility: "10+2 with MPC minimum 65% aggregate or JEE Mains / EAMCET rank.",
    totalSeats: 120,
    availableSeats: 22,
    applicationDeadline: "2026-09-15",
  },
  {
    id: "crs_003",
    organizationId: "org_abc_001",
    name: "B.Tech Electronics & Communication Engineering (ECE)",
    code: "BTECH-ECE",
    degree: "B.Tech",
    durationYears: 4,
    annualFeeINR: 120000,
    eligibility: "10+2 with MPC minimum 55% or EAMCET qualifier.",
    totalSeats: 180,
    availableSeats: 64,
    applicationDeadline: "2026-09-20",
  },
  {
    id: "crs_004",
    organizationId: "org_abc_001",
    name: "Master of Business Administration (MBA)",
    code: "MBA-GEN",
    degree: "MBA",
    durationYears: 2,
    annualFeeINR: 95000,
    eligibility: "Any recognized Bachelor's Degree with minimum 50% marks + TSICET / CAT / MAT score.",
    totalSeats: 120,
    availableSeats: 35,
    applicationDeadline: "2026-09-30",
  },
  {
    id: "crs_005",
    organizationId: "org_abc_001",
    name: "Diploma in Computer Engineering",
    code: "DIP-CME",
    degree: "Diploma",
    durationYears: 3,
    annualFeeINR: 45000,
    eligibility: "10th Standard / SSC pass with minimum 50% or POLYCET rank.",
    totalSeats: 60,
    availableSeats: 14,
    applicationDeadline: "2026-09-10",
  },
];

export const mockDocuments: KnowledgeDocument[] = [
  {
    id: "doc_001",
    organizationId: "org_abc_001",
    title: "ABC_College_Official_Admission_Prospectus_2026-27.pdf",
    category: "courses",
    fileType: "pdf",
    fileSizeBytes: 4850000,
    status: "indexed",
    chunkCount: 38,
    uploadedAt: "2026-08-15T09:20:00Z",
    lastIndexedAt: "2026-08-15T09:22:15Z",
  },
  {
    id: "doc_002",
    organizationId: "org_abc_001",
    title: "Fee_Structure_Scholarships_and_Payment_Schedules_2026.pdf",
    category: "fees",
    fileType: "pdf",
    fileSizeBytes: 1240000,
    status: "indexed",
    chunkCount: 16,
    uploadedAt: "2026-08-16T11:05:00Z",
    lastIndexedAt: "2026-08-16T11:06:30Z",
  },
  {
    id: "doc_003",
    organizationId: "org_abc_001",
    title: "Hostel_Rules_Mess_Menu_and_Campus_Facilities.docx",
    category: "hostel",
    fileType: "docx",
    fileSizeBytes: 890000,
    status: "indexed",
    chunkCount: 12,
    uploadedAt: "2026-08-18T14:12:00Z",
    lastIndexedAt: "2026-08-18T14:13:10Z",
  },
  {
    id: "doc_004",
    organizationId: "org_abc_001",
    title: "EAMCET_and_JEE_Previous_Year_Cutoff_Ranks.pdf",
    category: "eligibility",
    fileType: "pdf",
    fileSizeBytes: 2100000,
    status: "indexed",
    chunkCount: 22,
    uploadedAt: "2026-08-20T16:40:00Z",
    lastIndexedAt: "2026-08-20T16:41:45Z",
  },
  {
    id: "doc_005",
    organizationId: "org_abc_001",
    title: "Buses_Transportation_Routes_and_Pickup_Points.csv",
    category: "campus",
    fileType: "csv",
    fileSizeBytes: 320000,
    status: "indexed",
    chunkCount: 8,
    uploadedAt: "2026-08-22T10:15:00Z",
    lastIndexedAt: "2026-08-22T10:15:40Z",
  },
];

export const mockFAQs: FAQItem[] = [
  {
    id: "faq_001",
    organizationId: "org_abc_001",
    category: "admission_dates",
    question: "When is the last date to submit the B.Tech management quota application?",
    answer: "The last date for B.Tech Category-B / Management Quota applications for the 2026-27 academic year is September 15, 2026.",
    verified: true,
    updatedAt: "2026-08-25T12:00:00Z",
  },
  {
    id: "faq_002",
    organizationId: "org_abc_001",
    category: "hostel",
    question: "Are separate hostel facilities available for boys and girls?",
    answer: "Yes, ABC Institute provides separate high-security hostels for boys and girls with Wi-Fi, 24/7 power backup, hygienic South & North Indian food, and attached washroom options. Annual hostel fee is ₹75,000.",
    verified: true,
    updatedAt: "2026-08-25T12:05:00Z",
  },
  {
    id: "faq_003",
    organizationId: "org_abc_001",
    category: "fees",
    question: "Is there any merit scholarship for high EAMCET rankers?",
    answer: "Students with TSEAMCET rank below 5,000 get 100% tuition fee waiver. Ranks between 5,001 and 10,000 get 50% tuition waiver for the first year.",
    verified: true,
    updatedAt: "2026-08-25T12:10:00Z",
  },
  {
    id: "faq_004",
    organizationId: "org_abc_001",
    category: "documents",
    question: "What original documents are required during admission verification?",
    answer: "10th Marksheet, 12th/Intermediate Marksheet, Transfer Certificate (TC), Study/Conduct Certificates (6th to 12th), Caste/Income certificate (if applicable), TSEAMCET/JEE Rank card, and 6 passport photos.",
    verified: true,
    updatedAt: "2026-08-25T12:15:00Z",
  },
];

export const mockCalls: CallRecord[] = [
  {
    id: "call_101",
    organizationId: "org_abc_001",
    callerNumber: "+91 98765 43210",
    callerName: "Rahul Sharma",
    startedAt: "2026-08-30T14:32:10Z",
    durationSeconds: 224,
    status: "completed",
    primaryLanguage: "mixed",
    agentId: "agt_adm_001",
    agentName: "ABC Admission AI Counsellor",
    transcript: [
      {
        speaker: "ai",
        text: "Namaste and welcome to ABC Institute of Technology Admissions! How may I assist you today?",
        timestamp: "00:02",
        language: "en",
      },
      {
        speaker: "caller",
        text: "Hello madam, naaku B.Tech Computer Science CSE admission details and fee structure kaavali.",
        timestamp: "00:08",
        language: "te",
      },
      {
        speaker: "ai",
        text: "Certainly! The 4-year B.Tech in Computer Science and Engineering (CSE) has an annual tuition fee of ₹1,40,000. Eligibility requires a minimum 60% in Intermediate (10+2) with Maths, Physics, and Chemistry, or a valid TSEAMCET rank. Are you applying through Convener Quota or Management Quota?",
        timestamp: "00:22",
        language: "en",
      },
      {
        speaker: "caller",
        text: "Nenu Intermediate lo 88% vachindi. Management quota seat unda? Could a counsellor call me tomorrow afternoon?",
        timestamp: "00:38",
        language: "te",
      },
      {
        speaker: "ai",
        text: "With 88% in Intermediate MPC, you are well-qualified for Category-B Management Quota. We currently have 48 seats open. I have noted down your contact number and scheduled a senior admission counsellor to call you tomorrow between 2 PM and 3 PM. May I have your name, please?",
        timestamp: "00:58",
        language: "en",
      },
      {
        speaker: "caller",
        text: "My name is Rahul Sharma. Thank you so much!",
        timestamp: "01:10",
        language: "en",
      },
      {
        speaker: "ai",
        text: "Thank you, Rahul! Your callback request is confirmed. Have a great day and we look forward to welcoming you to ABC Institute!",
        timestamp: "01:22",
        language: "en",
      },
    ],
    aiSummary:
      "Caller Rahul Sharma enquired in Telugu/English about B.Tech CSE fee and management quota eligibility. He scored 88% in Intermediate MPC. AI confirmed fee (₹1.4L) and seat availability, captured lead details, and scheduled a counsellor callback for tomorrow afternoon.",
    leadId: "lead_001",
    leadStatus: "Highly Interested",
    keyTopicsDiscussed: ["B.Tech CSE", "Tuition Fee ₹1.4L", "Management Quota", "Callback Tomorrow 2 PM"],
  },
  {
    id: "call_102",
    organizationId: "org_abc_001",
    callerNumber: "+91 98451 12345",
    callerName: "Priya Patel",
    startedAt: "2026-08-30T13:15:00Z",
    durationSeconds: 145,
    status: "completed",
    primaryLanguage: "hi",
    agentId: "agt_adm_001",
    agentName: "ABC Admission AI Counsellor",
    transcript: [
      {
        speaker: "ai",
        text: "Namaste! ABC Institute of Technology Admissions mein aapka swaagat hai. Main aapki kya sahayata kar sakti hoon?",
        timestamp: "00:03",
        language: "hi",
      },
      {
        speaker: "caller",
        text: "Mujhe MBA admission eligibility aur hostel facility ke baare mein jaanna tha.",
        timestamp: "00:12",
        language: "hi",
      },
      {
        speaker: "ai",
        text: "ABC Institute mein 2-year MBA program ki annual fee ₹95,000 hai. Iske liye graduation mein kam se kam 50% marks aur TSICET ya CAT score zaroori hai. Hamare paas girls aur boys ke liye separate secure hostels hain jiska annual charge ₹75,000 hai.",
        timestamp: "00:32",
        language: "hi",
      },
      {
        speaker: "caller",
        text: "Bahut accha. Main application online download kar sakti hoon?",
        timestamp: "00:45",
        language: "hi",
      },
      {
        speaker: "ai",
        text: "Ji haan, aap abccollege.edu.in par jaakar online application form submit kar sakti hain. Deadline 30th September hai.",
        timestamp: "00:58",
        language: "hi",
      },
    ],
    aiSummary:
      "Priya Patel called to enquire about MBA admission eligibility, annual fee (₹95K), and hostel facilities (₹75K/yr). AI provided complete verified information and directed her to the online portal.",
    leadId: "lead_002",
    leadStatus: "Interested",
    keyTopicsDiscussed: ["MBA General", "Hostel Facilities", "Application Portal", "TSICET"],
  },
  {
    id: "call_103",
    organizationId: "org_abc_001",
    callerNumber: "+91 97001 98765",
    callerName: "Venkatesh Rao",
    startedAt: "2026-08-30T11:40:22Z",
    durationSeconds: 260,
    status: "transferred",
    primaryLanguage: "te",
    agentId: "agt_adm_001",
    agentName: "ABC Admission AI Counsellor",
    transcript: [
      {
        speaker: "ai",
        text: "Namaste and welcome to ABC Institute of Technology Admissions!",
        timestamp: "00:02",
        language: "en",
      },
      {
        speaker: "caller",
        text: "Sir, maaku EAMCET rank 3200 vachindi, kaani family financial situation valla fee concession kavali. Special scholarship quota unda?",
        timestamp: "00:15",
        language: "te",
      },
      {
        speaker: "ai",
        text: "Congratulations on securing rank 3,200! Under our institute policy, students with EAMCET ranks below 5,000 are eligible for a 100% tuition fee waiver. However, specific fee waiver approvals and hostel concessions require direct counselling evaluation. Let me transfer your call to our Senior Admission Officer Mr. S. K. Murthy right now.",
        timestamp: "00:38",
        language: "en",
      },
      {
        speaker: "ai",
        text: "[Transferring to +91 98480 22338... Connected]",
        timestamp: "00:45",
        language: "en",
      },
      {
        speaker: "human",
        text: "Hello Venkatesh garu, S. K. Murthy here. Let us review your rank card and income certificate for the 100% scholarship seat.",
        timestamp: "00:52",
        language: "te",
      },
    ],
    aiSummary:
      "Venkatesh Rao enquired about scholarship for EAMCET rank 3200 and economic fee concession. AI identified 100% tuition waiver eligibility and immediately executed human handoff to Chief Counsellor Mr. Murthy.",
    leadId: "lead_003",
    leadStatus: "Highly Interested",
    transferredTo: "+91 98480 22338 (Mr. S. K. Murthy)",
    transferReason: "Scholarship verification and fee waiver evaluation",
    keyTopicsDiscussed: ["EAMCET Rank 3200", "100% Scholarship", "Human Transfer", "B.Tech ECE"],
  },
  {
    id: "call_104",
    organizationId: "org_abc_001",
    callerNumber: "+91 99887 76655",
    callerName: "Ananya Sen",
    startedAt: "2026-08-30T10:05:12Z",
    durationSeconds: 110,
    status: "completed",
    primaryLanguage: "en",
    agentId: "agt_adm_001",
    agentName: "ABC Admission AI Counsellor",
    transcript: [
      {
        speaker: "ai",
        text: "Namaste! Welcome to ABC Institute of Technology Admissions. How can I assist you?",
        timestamp: "00:02",
        language: "en",
      },
      {
        speaker: "caller",
        text: "Hi, what is the application deadline for B.Tech in Artificial Intelligence & Data Science?",
        timestamp: "00:09",
        language: "en",
      },
      {
        speaker: "ai",
        text: "The application deadline for B.Tech AI & Data Science is September 15, 2026. The annual fee is ₹1,50,000 and we currently have 22 seats remaining out of 120. Would you like me to send you the application link via SMS?",
        timestamp: "00:26",
        language: "en",
      },
      {
        speaker: "caller",
        text: "Yes please, that would be helpful.",
        timestamp: "00:32",
        language: "en",
      },
    ],
    aiSummary:
      "Ananya Sen enquired about B.Tech AI & Data Science deadlines (Sept 15, 2026) and seat vacancy (22 left). Lead captured as New prospective applicant.",
    leadId: "lead_004",
    leadStatus: "New",
    keyTopicsDiscussed: ["B.Tech AI&DS", "Deadline Sept 15", "Seats Available: 22"],
  },
  {
    id: "call_105",
    organizationId: "org_abc_001",
    callerNumber: "+91 96123 45678",
    callerName: "Mohammed Farooq",
    startedAt: "2026-08-30T09:12:44Z",
    durationSeconds: 185,
    status: "completed",
    primaryLanguage: "mixed",
    agentId: "agt_adm_001",
    agentName: "ABC Admission AI Counsellor",
    transcript: [
      {
        speaker: "ai",
        text: "Namaste and welcome to ABC Institute of Technology Admissions! How may I help you?",
        timestamp: "00:02",
        language: "en",
      },
      {
        speaker: "caller",
        text: "Sir, ECE branch placements kaisa hai? Average package kya hai?",
        timestamp: "00:10",
        language: "hi",
      },
      {
        speaker: "ai",
        text: "For B.Tech ECE, ABC Institute achieved an 89% placement rate last academic year. The average package was ₹6.2 LPA, with the highest package reaching ₹21 LPA with top recruiters like Qualcomm, Texas Instruments, TCS, and Infosys. Would you like our placement report?",
        timestamp: "00:30",
        language: "en",
      },
      {
        speaker: "caller",
        text: "Yes, please ask a counsellor to call me today around 5 PM.",
        timestamp: "00:40",
        language: "en",
      },
    ],
    aiSummary:
      "Mohammed Farooq enquired in Hindi/English about ECE placements and highest package (₹21 LPA). Requested counsellor callback for today 5 PM.",
    leadId: "lead_005",
    leadStatus: "Callback Requested",
    keyTopicsDiscussed: ["B.Tech ECE Placements", "Avg Package ₹6.2 LPA", "Callback Today 5 PM"],
  },
];

export const mockLeads: LeadRecord[] = [
  {
    id: "lead_001",
    organizationId: "org_abc_001",
    studentName: "Rahul Sharma",
    phone: "+91 98765 43210",
    email: "rahul.sharma26@gmail.com",
    courseInterested: "B.Tech Computer Science & Engineering (CSE)",
    currentQualification: "Intermediate MPC (88%)",
    status: "Highly Interested",
    callbackRequested: true,
    preferredCallbackTime: "Tomorrow, 2:00 PM - 3:00 PM",
    assignedCounsellor: "Dr. K. S. Rao",
    notes: [
      {
        id: "note_1",
        author: "Admission AI",
        content: "Scored 88% in Inter MPC. Keen on B.Tech CSE Management Quota. Wants fee breakdown.",
        createdAt: "2026-08-30T14:35:00Z",
      },
    ],
    callIds: ["call_101"],
    createdAt: "2026-08-30T14:32:10Z",
    lastContactedAt: "2026-08-30T14:35:54Z",
  },
  {
    id: "lead_002",
    organizationId: "org_abc_001",
    studentName: "Priya Patel",
    phone: "+91 98451 12345",
    email: "priya.patel@outlook.com",
    courseInterested: "Master of Business Administration (MBA)",
    currentQualification: "B.Com (72%)",
    status: "Interested",
    callbackRequested: false,
    assignedCounsellor: "S. K. Murthy",
    notes: [
      {
        id: "note_2",
        author: "Admission AI",
        content: "Enquired about MBA eligibility and on-campus girls hostel.",
        createdAt: "2026-08-30T13:17:25Z",
      },
    ],
    callIds: ["call_102"],
    createdAt: "2026-08-30T13:15:00Z",
    lastContactedAt: "2026-08-30T13:17:25Z",
  },
  {
    id: "lead_003",
    organizationId: "org_abc_001",
    studentName: "Venkatesh Rao",
    phone: "+91 97001 98765",
    email: "venkat.rao99@yahoo.co.in",
    courseInterested: "B.Tech Electronics & Communication Engineering (ECE)",
    currentQualification: "Intermediate MPC (91%) - TSEAMCET Rank 3,200",
    status: "Highly Interested",
    callbackRequested: true,
    preferredCallbackTime: "Immediate (Transferred to Counsellor)",
    assignedCounsellor: "S. K. Murthy",
    notes: [
      {
        id: "note_3",
        author: "S. K. Murthy",
        content: "Spoke via live transfer. Qualified for 100% tuition waiver. Sent scholarship verification form.",
        createdAt: "2026-08-30T11:45:00Z",
      },
    ],
    callIds: ["call_103"],
    createdAt: "2026-08-30T11:40:22Z",
    lastContactedAt: "2026-08-30T11:45:00Z",
  },
  {
    id: "lead_004",
    organizationId: "org_abc_001",
    studentName: "Ananya Sen",
    phone: "+91 99887 76655",
    courseInterested: "B.Tech Artificial Intelligence & Machine Learning (AI&ML)",
    currentQualification: "CBSE 12th (84%)",
    status: "New",
    callbackRequested: false,
    notes: [
      {
        id: "note_4",
        author: "Admission AI",
        content: "Enquired about AI&ML deadline. Link sent via SMS.",
        createdAt: "2026-08-30T10:07:02Z",
      },
    ],
    callIds: ["call_104"],
    createdAt: "2026-08-30T10:05:12Z",
    lastContactedAt: "2026-08-30T10:07:02Z",
  },
  {
    id: "lead_005",
    organizationId: "org_abc_001",
    studentName: "Mohammed Farooq",
    phone: "+91 96123 45678",
    email: "farooq.m786@gmail.com",
    courseInterested: "B.Tech Electronics & Communication Engineering (ECE)",
    currentQualification: "Intermediate MPC (76%)",
    status: "Callback Requested",
    callbackRequested: true,
    preferredCallbackTime: "Today, 5:00 PM",
    assignedCounsellor: "Dr. K. S. Rao",
    notes: [
      {
        id: "note_5",
        author: "Admission AI",
        content: "Interested in ECE hardware lab facilities and top placements. Wants callback at 5 PM.",
        createdAt: "2026-08-30T09:15:49Z",
      },
    ],
    callIds: ["call_105"],
    createdAt: "2026-08-30T09:12:44Z",
    lastContactedAt: "2026-08-30T09:15:49Z",
  },
  {
    id: "lead_006",
    organizationId: "org_abc_001",
    studentName: "Sneha Reddy",
    phone: "+91 94401 23456",
    email: "sneha.reddy@gmail.com",
    courseInterested: "B.Tech Computer Science & Engineering (CSE)",
    currentQualification: "Intermediate MPC (94%)",
    status: "Converted",
    callbackRequested: false,
    assignedCounsellor: "Dr. K. S. Rao",
    notes: [
      {
        id: "note_6",
        author: "Dr. K. S. Rao",
        content: "Admission completed. First semester fee paid on 28 Aug 2026.",
        createdAt: "2026-08-28T16:00:00Z",
      },
    ],
    callIds: [],
    createdAt: "2026-08-27T10:00:00Z",
    lastContactedAt: "2026-08-28T16:00:00Z",
  },
  {
    id: "lead_007",
    organizationId: "org_abc_001",
    studentName: "Rajesh Kumar",
    phone: "+91 93901 88888",
    courseInterested: "Diploma in Computer Engineering",
    currentQualification: "SSC (78%)",
    status: "Lost",
    callbackRequested: false,
    notes: [
      {
        id: "note_7",
        author: "S. K. Murthy",
        content: "Opted for government polytechnic college near hometown.",
        createdAt: "2026-08-26T11:20:00Z",
      },
    ],
    callIds: [],
    createdAt: "2026-08-25T09:30:00Z",
    lastContactedAt: "2026-08-26T11:20:00Z",
  },
];

export const mockFollowUps: FollowUpItem[] = [
  {
    id: "flw_001",
    organizationId: "org_abc_001",
    leadId: "lead_005",
    studentName: "Mohammed Farooq",
    phone: "+91 96123 45678",
    courseInterested: "B.Tech Electronics & Communication (ECE)",
    scheduledFor: "2026-08-30T17:00:00Z",
    status: "pending",
    priority: "high",
    assignedTo: "Dr. K. S. Rao",
    notes: "Call to explain ECE lab infrastructure and placement packages.",
    createdAt: "2026-08-30T09:15:49Z",
  },
  {
    id: "flw_002",
    organizationId: "org_abc_001",
    leadId: "lead_001",
    studentName: "Rahul Sharma",
    phone: "+91 98765 43210",
    courseInterested: "B.Tech Computer Science & Engineering (CSE)",
    scheduledFor: "2026-08-31T14:00:00Z",
    status: "pending",
    priority: "high",
    assignedTo: "Dr. K. S. Rao",
    notes: "Follow up on B.Tech CSE management quota application token.",
    createdAt: "2026-08-30T14:35:00Z",
  },
  {
    id: "flw_003",
    organizationId: "org_abc_001",
    leadId: "lead_003",
    studentName: "Venkatesh Rao",
    phone: "+91 97001 98765",
    courseInterested: "B.Tech Electronics & Communication (ECE)",
    scheduledFor: "2026-08-31T11:00:00Z",
    status: "pending",
    priority: "medium",
    assignedTo: "S. K. Murthy",
    notes: "Verify submission of income certificate for 100% tuition waiver.",
    createdAt: "2026-08-30T11:45:00Z",
  },
  {
    id: "flw_004",
    organizationId: "org_abc_001",
    leadId: "lead_002",
    studentName: "Priya Patel",
    phone: "+91 98451 12345",
    courseInterested: "Master of Business Administration (MBA)",
    scheduledFor: "2026-08-29T15:00:00Z",
    status: "completed",
    priority: "medium",
    assignedTo: "S. K. Murthy",
    notes: "Completed follow-up. Sent campus tour invite.",
    createdAt: "2026-08-28T14:00:00Z",
  },
];

export const mockPhoneNumbers: PhoneNumberRecord[] = [
  {
    id: "phn_001",
    organizationId: "org_abc_001",
    number: "+918047198800",
    formattedNumber: "+91 80 4719 8800",
    provider: "Exotel (Planned)",
    status: "active",
    assignedAgentName: "ABC Admission AI Counsellor",
    fallbackNumber: "+91 98480 22338",
    monthlyRentalINR: 1999,
    totalCallsHandled: 1482,
    activatedAt: "2026-08-01T00:00:00Z",
  },
  {
    id: "phn_002",
    organizationId: "org_abc_001",
    number: "+914069324400",
    formattedNumber: "+91 40 6932 4400",
    provider: "Virtual Cloud",
    status: "reserved",
    assignedAgentName: "Unassigned (Secondary Line)",
    fallbackNumber: "+91 98480 22338",
    monthlyRentalINR: 1499,
    totalCallsHandled: 0,
    activatedAt: "2026-08-28T00:00:00Z",
  },
];

export const mockPlans: SubscriptionPlan[] = [
  {
    id: "basic",
    name: "Basic Admission Starter",
    tagline: "Ideal for single-campus schools and coaching centers",
    priceMonthlyINR: 4999,
    voiceMinutesIncluded: 500,
    voiceMinutesUsed: 420,
    phoneNumbersIncluded: 1,
    phoneNumbersUsed: 1,
    whatsappEnabled: false,
    knowledgeDocsLimit: 10,
    knowledgeDocsUsed: 5,
    maxStaffUsers: 2,
    features: [
      "1 Indian Virtual Phone Number",
      "Admission AI Counsellor (EN, HI, TE)",
      "Basic Knowledge Base & FAQ Indexing",
      "Inbound Call Recording & Transcripts",
      "Structured Lead Qualification CRM",
      "Human Counsellor Handoff",
      "Standard Analytics",
    ],
  },
  {
    id: "pro",
    name: "Pro Institute Growth",
    tagline: "Designed for leading colleges, universities & large institutes",
    priceMonthlyINR: 12999,
    voiceMinutesIncluded: 2500,
    voiceMinutesUsed: 1482,
    phoneNumbersIncluded: 3,
    phoneNumbersUsed: 1,
    whatsappEnabled: true,
    knowledgeDocsLimit: 50,
    knowledgeDocsUsed: 5,
    maxStaffUsers: 10,
    features: [
      "Up to 3 Indian Virtual Phone Numbers",
      "High-Performance Admission AI with Multilingual Code-Mixing",
      "WhatsApp Business Integration",
      "Unlimited Structured Lead Management",
      "Scheduled Callback Automation",
      "Custom Knowledge Categorization & Instant RAG Updates",
      "Advanced Conversion & Admission Funnel Analytics",
      "Dedicated Human Transfer Fallback Routing",
      "10 Staff Counsellor Accounts with RBAC",
    ],
  },
  {
    id: "enterprise",
    name: "Enterprise Multi-Campus",
    tagline: "For university systems, multi-branch groups & large institutions",
    priceMonthlyINR: 29999,
    voiceMinutesIncluded: 10000,
    voiceMinutesUsed: 1482,
    phoneNumbersIncluded: 10,
    phoneNumbersUsed: 1,
    whatsappEnabled: true,
    knowledgeDocsLimit: 500,
    knowledgeDocsUsed: 5,
    maxStaffUsers: 50,
    features: [
      "10+ Indian Toll-free & Virtual Phone Numbers",
      "Custom Fine-Tuned Voice & Pronunciation Dictionaries",
      "ERP & CRM Webhook Synchronizations",
      "Multi-Campus Tenant Partitioning",
      "Custom SLA & 24/7 Priority Support",
      "Automated WhatsApp Campaign & Follow-up Triggers",
      "Dedicated Account Manager",
    ],
  },
];

export const mockAnalytics: AnalyticsSummary = {
  totalCalls: 1482,
  answeredCalls: 1448,
  aiHandledPercentage: 91.4,
  humanTransfers: 128,
  totalLeadsCaptured: 846,
  highlyInterestedLeads: 312,
  conversions: 84,
  avgCallDurationSeconds: 168,
  callTrends: [
    { date: "Aug 24", calls: 184, leads: 102, transfers: 14 },
    { date: "Aug 25", calls: 210, leads: 124, transfers: 18 },
    { date: "Aug 26", calls: 195, leads: 110, transfers: 15 },
    { date: "Aug 27", calls: 242, leads: 148, transfers: 22 },
    { date: "Aug 28", calls: 268, leads: 165, transfers: 24 },
    { date: "Aug 29", calls: 215, leads: 132, transfers: 19 },
    { date: "Aug 30", calls: 168, leads: 95, transfers: 16 },
  ],
  languageBreakdown: [
    { language: "English", percentage: 48, count: 711 },
    { language: "Telugu", percentage: 32, count: 474 },
    { language: "Hindi", percentage: 20, count: 297 },
  ],
  topCourses: [
    { name: "B.Tech CSE", enquiries: 642, leads: 384 },
    { name: "B.Tech AI&ML", enquiries: 410, leads: 248 },
    { name: "B.Tech ECE", enquiries: 260, leads: 132 },
    { name: "MBA General", enquiries: 110, leads: 58 },
    { name: "Diploma Computer", enquiries: 60, leads: 24 },
  ],
  hourlyVolume: [
    { hour: "8 AM", calls: 42 },
    { hour: "9 AM", calls: 118 },
    { hour: "10 AM", calls: 210 },
    { hour: "11 AM", calls: 265 },
    { hour: "12 PM", calls: 195 },
    { hour: "1 PM", calls: 120 },
    { hour: "2 PM", calls: 175 },
    { hour: "3 PM", calls: 230 },
    { hour: "4 PM", calls: 188 },
    { hour: "5 PM", calls: 142 },
    { hour: "6 PM", calls: 82 },
    { hour: "7 PM", calls: 35 },
  ],
};
